//
//     Generated by class-dump 3.5-MH (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import <MUIKit/MUIDefines.h>

NS_ASSUME_NONNULL_BEGIN

@interface MUIAlertController : UIAlertController

@property (nonatomic) BOOL didPerformAction; // @synthesize didPerformAction=_didPerformAction;
@property (copy, nonatomic) void (^dissmissWithoutActionBlock)(void); // @synthesize dissmissWithoutActionBlock=_dissmissWithoutActionBlock;

- (void)dealloc;

@end

NS_ASSUME_NONNULL_END
